site_name: LaCE Documentation
theme:
  name: material

# Define the navigation structure for the docs
nav:
  - Home: index.md
  - Installation: installation.md
  - Emulator:
    - Training: emulatorTraining.md
    - Predictions: emulatorPredictions.md
  - Advanced:
    - Compressed Parameters: compressedParameters.md
  - Archive: archive.md

# Define the URL where the site will be deployed
site_url: https://github.com/igmhub/LaCE

markdown_extensions:
  - codehilite
  - toc
  - admonition