site_name: LaCE Documentation
theme:
  name: material

# Define the navigation structure for the docs
nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide:
    - Overview: users/index.md
    - Available Simulations: users/Simulations_list.md
    - Emulators and Training Sets: users/Emulators_trainingSets.md
    - Archive: users/archive.md
    - Emulator Training: users/emulatorTraining.md
    - Emulator Predictions: users/emulatorPredictions.md 
    - Compressed Parameters: users/compressedParameters.md
    
  - Developer Guide:
    - Overview: developers/index.md
    - Creating New Emulators: developers/CreateNewEmulator.md
    - Training Options: developers/trainingOptions.md
    - Testing: developers/advancedTesting.md
    - Documentation: developers/documentation.md

# Define the URL where the site will be deployed
site_url: https://github.com/igmhub/LaCE

markdown_extensions:
  - codehilite
  - toc
  - admonition